title: Jiayi Wen's Homepage
page-top-title: Jiayi Wen
top-section-bg-text: Wearable Robotics & Exoskeletons
home-subtitle: Jiayi Wen&ensp;|&ensp;温嘉懿
copyright-text: '&copy; Jiayi Wen 2021-2025. All Rights Reserved.'
